FROM ubuntu:bionic

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    build-essential \
    automake ca-certificates openssl \
    zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev libelf-dev \
    vim curl file

ENV DAPPER_SOURCE /source
ENV DAPPER_OUTPUT ./dist
ENV DAPPER_ENV OS_KERNEL ZFS

WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
